### ISSUE TITLE
base64url versus base64-url

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [brianloveswords/node-jwa#14]
`jwa` depends on `base64url`.  But it also depends on `ecdsa-sig-formatter`, which depends on `base64-url`.  Would it reduce the total number of dependencies to replace `base64url` with `base64-url`?

**Comment by marco-c** [comment]
I agree, I know you're the author of `base64url`, but reducing the dependencies is worthwhile and the base64 implementation is really simple anyway.
