### ISSUE TITLE
Wrong curve used in Makefile

### ISSUE THREAD

**Issue by OscarAyoy** [brianloveswords/node-jwa#2]
Hi!

I think I've spotted a mistake in your Makefile. The test keys you are generating for ES256  are using a Koblitz elliptic curve (which OpenSSL refers to as "secp256k1") as opposed to the appropriate Suite B P-256 Prime field curve  (which OpenSSL refers to as "prime256v1"). I think a simple s/secp256k1/prime256v1/ should do the trick.

**Comment by brianloveswords** [comment]
Fix has been made!
