### ISSUE TITLE
Insecure dependency base64url < 3.0.0

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [brianloveswords/node-jwa#29]
Dependency base64url^2.0.0 is not secure per [NSP advisory 658](https://nodesecurity.io/advisories/658)

Please consider updating! Thanks

**Comment by omsmith** [comment]
It's a dev dependency and shouldn't cause any warnings on `npm install` or the like unless you're cloning the repo and installing them to do development. If I'm mistaken on that, please let me know!

Ref: https://github.com/brianloveswords/node-jwa/pull/27

**Comment by alex-thewsey-ibm** [comment]
Interesting point thanks @omsmith! It's flagging as an NSP error in one of our toolchains (which installs DevDependencies in order to perform a build step) - but I'll investigate whether it's possible/sensible to update our NSP check config to ignore.

**Comment by omsmith** [comment]
Thanks @alex-thewsey-ibm, glad you got it sorted.
