### ISSUE TITLE
Can't resolve 'crypto'

### ISSUE THREAD

**Issue by Mondei1** [brianloveswords/node-jwa#35]
Today, I upgraded my angular project and suddenly I get this error:
```
ERROR in ./node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/.../node_modules/jwa'
```
I have node v11.11.0 installed and there is `crypto` built-in and the old library is no longer supported. My current `jwa` version is the latest (1.4.1).

I don't know If I messed something up or it's the library. Don't hate me If it's a really stupid question :cry:

**Comment by omsmith** [comment]
Certainly an angular problem, not providing a polyfill for crypto.

Perhaps https://github.com/auth0/node-jsonwebtoken/issues/471 will provide some insight?
