### ISSUE TITLE
Handle RSA passphrase

### ISSUE THREAD

**Issue by alexandrebodin** [brianloveswords/node-jwa#6]
Hello,

I would like to use a {key : cert, passphrase: 'pass'} has key to pass on to the crypto lib for signing and using protected pem files.

Looking at the NodeJs [Crypto documentation](https://nodejs.org/api/crypto.html#crypto_sign_sign_private_key_output_format) I found that this is faisable. 

The only problem is that you check if the provided key is a buffer or a string. I believe this is not necessary as the lib handles it.

**Comment by alexandrebodin** [comment]
I'm gonne

**Comment by alexandrebodin** [comment]
The PR #7  fixes it

**Comment by omsmith** [comment]
Fixed by #7.

Published in _1.1.0_
